extern crate rustc_serialize;

use self::rustc_serialize::json::Json;

use lexer::RegexLexer;
use lexer::RegexLexerError;



type Token = usize;
type State = usize;
type ProdIndex = usize;

#[derive(Debug)]
struct ProductionItem {
    header_id: usize,
    body_length: usize,
}

#[derive(Debug, Copy, Clone)]
enum Action {
    Reduce(ProdIndex),
    Shift(State),
    Accept,
    Goto(State),
    Error,
}

#[derive(Debug)]
pub struct Parser {
    prod_list: Vec<ProductionItem>,
    lookup_table: Vec<Action>,
}

impl Parser {
    pub fn new() -> Parser {
        Parser {
            prod_list: vec![ProductionItem {
                                header_id: 25,
                                body_length: 2,
                            },
                            ProductionItem {
                                header_id: 19,
                                body_length: 1,
                            },
                            ProductionItem {
                                header_id: 19,
                                body_length: 4,
                            },
                            ProductionItem {
                                header_id: 21,
                                body_length: 2,
                            },
                            ProductionItem {
                                header_id: 21,
                                body_length: 0,
                            },
                            ProductionItem {
                                header_id: 20,
                                body_length: 3,
                            },
                            ProductionItem {
                                header_id: 20,
                                body_length: 3,
                            },
                            ProductionItem {
                                header_id: 20,
                                body_length: 2,
                            },
                            ProductionItem {
                                header_id: 20,
                                body_length: 2,
                            },
                            ProductionItem {
                                header_id: 20,
                                body_length: 2,
                            },
                            ProductionItem {
                                header_id: 20,
                                body_length: 2,
                            },
                            ProductionItem {
                                header_id: 20,
                                body_length: 3,
                            },
                            ProductionItem {
                                header_id: 20,
                                body_length: 4,
                            },
                            ProductionItem {
                                header_id: 20,
                                body_length: 2,
                            },
                            ProductionItem {
                                header_id: 20,
                                body_length: 1,
                            },
                            ProductionItem {
                                header_id: 23,
                                body_length: 3,
                            },
                            ProductionItem {
                                header_id: 23,
                                body_length: 4,
                            },
                            ProductionItem {
                                header_id: 23,
                                body_length: 5,
                            },
                            ProductionItem {
                                header_id: 23,
                                body_length: 4,
                            },
                            ProductionItem {
                                header_id: 24,
                                body_length: 4,
                            },
                            ProductionItem {
                                header_id: 24,
                                body_length: 2,
                            },
                            ProductionItem {
                                header_id: 24,
                                body_length: 1,
                            },
                            ProductionItem {
                                header_id: 24,
                                body_length: 3,
                            },
                            ProductionItem {
                                header_id: 22,
                                body_length: 1,
                            },
                            ProductionItem {
                                header_id: 22,
                                body_length: 1,
                            }],
            lookup_table: vec![Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Reduce(23),
                               Action::Reduce(24),
                               Action::Accept,
                               Action::Reduce(1),
                               Action::Reduce(14),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Reduce(8),
                               Action::Reduce(9),
                               Action::Reduce(10),
                               Action::Error,
                               Action::Reduce(13),
                               Action::Reduce(7),
                               Action::Reduce(4),
                               Action::Reduce(6),
                               Action::Error,
                               Action::Error,
                               Action::Reduce(11),
                               Action::Error,
                               Action::Error,
                               Action::Reduce(5),
                               Action::Error,
                               Action::Error,
                               Action::Reduce(2),
                               Action::Reduce(12),
                               Action::Error,
                               Action::Error,
                               Action::Reduce(15),
                               Action::Error,
                               Action::Error,
                               Action::Reduce(3),
                               Action::Error,
                               Action::Error,
                               Action::Reduce(18),
                               Action::Reduce(16),
                               Action::Reduce(17),
                               Action::Shift(2),
                               Action::Shift(2),
                               Action::Shift(2),
                               Action::Error,
                               Action::Reduce(23),
                               Action::Reduce(24),
                               Action::Error,
                               Action::Shift(2),
                               Action::Reduce(14),
                               Action::Shift(2),
                               Action::Shift(2),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Shift(2),
                               Action::Reduce(8),
                               Action::Reduce(9),
                               Action::Reduce(10),
                               Action::Error,
                               Action::Reduce(13),
                               Action::Reduce(7),
                               Action::Error,
                               Action::Reduce(6),
                               Action::Error,
                               Action::Error,
                               Action::Reduce(11),
                               Action::Error,
                               Action::Error,
                               Action::Shift(2),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Reduce(12),
                               Action::Error,
                               Action::Error,
                               Action::Reduce(15),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Reduce(18),
                               Action::Reduce(16),
                               Action::Reduce(17),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Reduce(23),
                               Action::Reduce(24),
                               Action::Error,
                               Action::Error,
                               Action::Reduce(14),
                               Action::Error,
                               Action::Shift(23),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Reduce(8),
                               Action::Reduce(9),
                               Action::Reduce(10),
                               Action::Error,
                               Action::Reduce(13),
                               Action::Reduce(7),
                               Action::Error,
                               Action::Reduce(6),
                               Action::Error,
                               Action::Error,
                               Action::Reduce(11),
                               Action::Error,
                               Action::Error,
                               Action::Reduce(5),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Reduce(12),
                               Action::Error,
                               Action::Error,
                               Action::Reduce(15),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Reduce(18),
                               Action::Reduce(16),
                               Action::Reduce(17),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Reduce(23),
                               Action::Reduce(24),
                               Action::Error,
                               Action::Shift(16),
                               Action::Reduce(14),
                               Action::Shift(16),
                               Action::Shift(16),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Reduce(8),
                               Action::Reduce(9),
                               Action::Reduce(10),
                               Action::Error,
                               Action::Shift(16),
                               Action::Reduce(7),
                               Action::Error,
                               Action::Reduce(6),
                               Action::Error,
                               Action::Error,
                               Action::Reduce(11),
                               Action::Error,
                               Action::Error,
                               Action::Shift(16),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Reduce(12),
                               Action::Error,
                               Action::Error,
                               Action::Reduce(15),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Reduce(18),
                               Action::Reduce(16),
                               Action::Reduce(17),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Reduce(23),
                               Action::Reduce(24),
                               Action::Error,
                               Action::Shift(17),
                               Action::Reduce(14),
                               Action::Shift(17),
                               Action::Shift(17),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Reduce(8),
                               Action::Reduce(9),
                               Action::Reduce(10),
                               Action::Error,
                               Action::Shift(17),
                               Action::Reduce(7),
                               Action::Error,
                               Action::Reduce(6),
                               Action::Error,
                               Action::Error,
                               Action::Reduce(11),
                               Action::Error,
                               Action::Error,
                               Action::Shift(17),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Reduce(12),
                               Action::Error,
                               Action::Error,
                               Action::Reduce(15),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Reduce(18),
                               Action::Reduce(16),
                               Action::Reduce(17),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Shift(31),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Shift(37),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Shift(25),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Shift(35),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Shift(1),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Reduce(23),
                               Action::Reduce(24),
                               Action::Error,
                               Action::Error,
                               Action::Reduce(14),
                               Action::Shift(22),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Reduce(8),
                               Action::Reduce(9),
                               Action::Reduce(10),
                               Action::Error,
                               Action::Reduce(13),
                               Action::Reduce(7),
                               Action::Error,
                               Action::Reduce(6),
                               Action::Error,
                               Action::Error,
                               Action::Reduce(11),
                               Action::Error,
                               Action::Error,
                               Action::Reduce(5),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Reduce(12),
                               Action::Error,
                               Action::Error,
                               Action::Reduce(15),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Reduce(18),
                               Action::Reduce(16),
                               Action::Reduce(17),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Reduce(23),
                               Action::Reduce(24),
                               Action::Error,
                               Action::Shift(18),
                               Action::Reduce(14),
                               Action::Shift(18),
                               Action::Shift(18),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Reduce(8),
                               Action::Reduce(9),
                               Action::Reduce(10),
                               Action::Error,
                               Action::Shift(18),
                               Action::Reduce(7),
                               Action::Error,
                               Action::Reduce(6),
                               Action::Error,
                               Action::Error,
                               Action::Reduce(11),
                               Action::Error,
                               Action::Error,
                               Action::Shift(18),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Reduce(12),
                               Action::Error,
                               Action::Error,
                               Action::Reduce(15),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Reduce(18),
                               Action::Reduce(16),
                               Action::Reduce(17),
                               Action::Shift(3),
                               Action::Shift(3),
                               Action::Shift(3),
                               Action::Error,
                               Action::Reduce(23),
                               Action::Reduce(24),
                               Action::Error,
                               Action::Shift(3),
                               Action::Reduce(14),
                               Action::Shift(3),
                               Action::Shift(3),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Shift(3),
                               Action::Reduce(8),
                               Action::Reduce(9),
                               Action::Reduce(10),
                               Action::Error,
                               Action::Reduce(13),
                               Action::Reduce(7),
                               Action::Error,
                               Action::Reduce(6),
                               Action::Error,
                               Action::Error,
                               Action::Reduce(11),
                               Action::Error,
                               Action::Error,
                               Action::Shift(3),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Reduce(12),
                               Action::Error,
                               Action::Error,
                               Action::Reduce(15),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Reduce(18),
                               Action::Reduce(16),
                               Action::Reduce(17),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Reduce(24),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Reduce(23),
                               Action::Reduce(21),
                               Action::Shift(26),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Shift(33),
                               Action::Error,
                               Action::Error,
                               Action::Reduce(23),
                               Action::Reduce(20),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Reduce(22),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Reduce(19),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Shift(11),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Shift(4),
                               Action::Shift(4),
                               Action::Shift(4),
                               Action::Shift(12),
                               Action::Reduce(23),
                               Action::Reduce(24),
                               Action::Error,
                               Action::Shift(4),
                               Action::Reduce(14),
                               Action::Shift(4),
                               Action::Shift(4),
                               Action::Shift(12),
                               Action::Reduce(23),
                               Action::Reduce(21),
                               Action::Shift(27),
                               Action::Shift(4),
                               Action::Reduce(8),
                               Action::Reduce(9),
                               Action::Reduce(10),
                               Action::Error,
                               Action::Reduce(13),
                               Action::Reduce(7),
                               Action::Reduce(4),
                               Action::Reduce(6),
                               Action::Shift(27),
                               Action::Shift(34),
                               Action::Reduce(11),
                               Action::Reduce(23),
                               Action::Reduce(20),
                               Action::Shift(4),
                               Action::Error,
                               Action::Error,
                               Action::Shift(4),
                               Action::Reduce(12),
                               Action::Reduce(22),
                               Action::Shift(40),
                               Action::Reduce(15),
                               Action::Error,
                               Action::Error,
                               Action::Reduce(3),
                               Action::Reduce(19),
                               Action::Error,
                               Action::Reduce(18),
                               Action::Reduce(16),
                               Action::Reduce(17),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Shift(30),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Shift(38),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Shift(41),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Shift(5),
                               Action::Shift(5),
                               Action::Shift(5),
                               Action::Shift(5),
                               Action::Reduce(23),
                               Action::Reduce(24),
                               Action::Error,
                               Action::Shift(5),
                               Action::Reduce(14),
                               Action::Shift(5),
                               Action::Shift(5),
                               Action::Shift(5),
                               Action::Reduce(23),
                               Action::Reduce(21),
                               Action::Shift(5),
                               Action::Shift(5),
                               Action::Reduce(8),
                               Action::Reduce(9),
                               Action::Reduce(10),
                               Action::Error,
                               Action::Reduce(13),
                               Action::Reduce(7),
                               Action::Reduce(4),
                               Action::Reduce(6),
                               Action::Shift(5),
                               Action::Error,
                               Action::Reduce(11),
                               Action::Reduce(23),
                               Action::Reduce(20),
                               Action::Shift(5),
                               Action::Error,
                               Action::Error,
                               Action::Shift(5),
                               Action::Reduce(12),
                               Action::Reduce(22),
                               Action::Error,
                               Action::Reduce(15),
                               Action::Error,
                               Action::Error,
                               Action::Reduce(3),
                               Action::Reduce(19),
                               Action::Error,
                               Action::Reduce(18),
                               Action::Reduce(16),
                               Action::Reduce(17),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Reduce(23),
                               Action::Reduce(24),
                               Action::Error,
                               Action::Shift(19),
                               Action::Reduce(14),
                               Action::Shift(19),
                               Action::Shift(19),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Reduce(8),
                               Action::Reduce(9),
                               Action::Reduce(10),
                               Action::Error,
                               Action::Shift(19),
                               Action::Reduce(7),
                               Action::Error,
                               Action::Reduce(6),
                               Action::Error,
                               Action::Error,
                               Action::Reduce(11),
                               Action::Error,
                               Action::Error,
                               Action::Shift(19),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Reduce(12),
                               Action::Error,
                               Action::Error,
                               Action::Reduce(15),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Reduce(18),
                               Action::Reduce(16),
                               Action::Reduce(17),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Reduce(23),
                               Action::Reduce(24),
                               Action::Error,
                               Action::Shift(15),
                               Action::Reduce(14),
                               Action::Shift(15),
                               Action::Shift(15),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Reduce(8),
                               Action::Reduce(9),
                               Action::Reduce(10),
                               Action::Error,
                               Action::Reduce(13),
                               Action::Reduce(7),
                               Action::Error,
                               Action::Reduce(6),
                               Action::Error,
                               Action::Error,
                               Action::Reduce(11),
                               Action::Error,
                               Action::Error,
                               Action::Reduce(5),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Reduce(12),
                               Action::Error,
                               Action::Error,
                               Action::Reduce(15),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Reduce(18),
                               Action::Reduce(16),
                               Action::Reduce(17),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Shift(36),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Shift(42),
                               Action::Shift(43),
                               Action::Error,
                               Action::Error,
                               Action::Shift(44),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Goto(6),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Goto(7),
                               Action::Goto(9),
                               Action::Goto(10),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Goto(20),
                               Action::Error,
                               Action::Goto(20),
                               Action::Goto(20),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Goto(29),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Goto(20),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Goto(20),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Goto(32),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Goto(8),
                               Action::Goto(8),
                               Action::Goto(8),
                               Action::Goto(13),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Goto(8),
                               Action::Error,
                               Action::Goto(8),
                               Action::Goto(8),
                               Action::Goto(13),
                               Action::Error,
                               Action::Error,
                               Action::Goto(28),
                               Action::Goto(8),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Goto(8),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Goto(28),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Goto(8),
                               Action::Error,
                               Action::Error,
                               Action::Goto(39),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Goto(21),
                               Action::Error,
                               Action::Goto(21),
                               Action::Goto(21),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Goto(21),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Goto(21),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Goto(14),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Goto(24),
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error,
                               Action::Error],
        }
    }

    fn lookup(&self, token: Token, state: State) -> Action {
        let input_length: usize = 25;
        let state_length: usize = 45;
        if token >= input_length || state >= state_length {
            return Action::Error;
        }
        return self.lookup_table[token * state_length + state].clone();
    }

    pub fn parse(&self, lexer: &mut RegexLexer) -> Result<Json, RegexLexerError> {

        let mut codes: Vec<Json> = Vec::new();
        let mut flags: Vec<Json> = Vec::new();

        let mut state_stack: Vec<State> = vec![0];
        let mut output_stack: Vec<Json> = Vec::new();

        loop {
            let token = match lexer.get_token() {
                Ok(token) => token,
                Err(err) => return Err(err),
            };
            let state = state_stack[state_stack.len() - 1];
            let action = self.lookup(token, state);
            // println!("{:?}", ("cur_state", state, "token", RegexLexer::find_token_name(token), token, lexer.get_yytext(), "action", action));
            match action {
                Action::Accept => {
                    return Ok(output_stack.pop().unwrap());
                }
                Action::Shift(next_state) => {
                    output_stack.push(lexer.get_yytext());
                    state_stack.push(next_state);
                    lexer.advance();
                }
                Action::Reduce(prod_index) => {
                    let length = self.prod_list[prod_index].body_length;
                    let mut _result: Option<Json> = None;
                    match prod_index {
                        0x1 => {
                            _result = Some(Json::Array(codes.clone()));
                        }
                        0x2 => {

                            for _ in 0..flags.len() {
                                codes.pop();
                            }
                            _result = Some(Json::Array(codes.clone()));

                        }
                        0x3 => {

                            let flags_c = (output_stack[output_stack.len() - 1].clone());
                            if flags.contains(&flags_c) {
                                return Err(lexer.new_lexer_error("Flag Repeated".to_string()));
                            }
                            if "igm".find(flags_c.as_string().unwrap()).is_none() {
                                return Err(lexer.new_lexer_error("Unknow Flag".to_string()));
                            }
                            flags.push(flags_c);

                        }
                        0x4 => {}
                        0x5 => {
                            codes.push(Json::String("or".to_string()));
                        }
                        0x6 => {}
                        0x7 => {}
                        0x8 => {
                            codes.push(Json::String("star".to_string()));
                        }
                        0x9 => {
                            codes.push(Json::String("more".to_string()));
                        }
                        0xA => {
                            codes.push(Json::String("ask".to_string()));
                        }
                        0xB => {
                            codes.push(Json::Array(vec![Json::String("include".to_string()),
                                                        (output_stack[output_stack.len() - 2]
                                                            .clone())]));
                        }
                        0xC => {
                            codes.push(Json::Array(vec![Json::String("exclude".to_string()),
                                                        (output_stack[output_stack.len() - 2]
                                                            .clone())]));
                        }
                        0xD => {
                            codes.push(Json::String("cat".to_string()));
                        }
                        0xE => {
                            codes.push(Json::String("single".to_string()));
                        }
                        0xF => {

                            let n: u64 = (output_stack[output_stack.len() - 2].clone())
                                .as_u64()
                                .unwrap() - 1;
                            for _ in 0..n {
                                codes.push(Json::String("dupl".to_string()));
                            }
                            for _ in 0..n {
                                codes.push(Json::String("cat".to_string()));
                            }

                        }
                        0x10 => {

                            codes.push(Json::String("ask".to_string()));
                            let n: u64 = (output_stack[output_stack.len() - 2].clone())
                                .as_u64()
                                .unwrap() - 1;
                            for _ in 0..n {
                                codes.push(Json::String("dupl".to_string()));
                            }
                            for _ in 0..n {
                                codes.push(Json::String("cat".to_string()));
                            }

                        }
                        0x11 => {

                            let mut n: u64 = (output_stack[output_stack.len() - 4].clone())
                                .as_u64()
                                .unwrap() - 1;
                            for _ in 0..n {
                                codes.push(Json::String("dupl".to_string()));
                            }
                            n = (output_stack[output_stack.len() - 2].clone()).as_u64().unwrap() -
                                n;
                            if n > 0 {
                                codes.push(Json::String("dupl".to_string()));
                                codes.push(Json::String("ask".to_string()));
                                for _ in 0..n {
                                    codes.push(Json::String("dupl".to_string()));
                                }
                            }
                            n = (output_stack[output_stack.len() - 2].clone()).as_u64().unwrap() -
                                1;
                            for _ in 0..n {
                                codes.push(Json::String("cat".to_string()));
                            }

                        }
                        0x12 => {

                            let n: u64 =
                                (output_stack[output_stack.len() - 3].clone()).as_u64().unwrap();
                            for _ in 0..n {
                                codes.push(Json::String("dupl".to_string()));
                            }
                            codes.push(Json::String("star".to_string()));
                            for _ in 0..n {
                                codes.push(Json::String("cat".to_string()));
                            }

                        }
                        0x13 => {
                            _result =
                                Some(Json::U64((output_stack[output_stack.len() - 4].clone())
                                    .as_u64()
                                    .unwrap() + 1));
                            codes.push(Json::Array(vec![Json::String("c".to_string()),
                                                        (output_stack[output_stack.len() - 3]
                                                            .clone())]));
                            codes.push(Json::Array(vec![Json::String("c".to_string()),
                                                        (output_stack[output_stack.len() - 1]
                                                            .clone())]));
                            codes.push(Json::String("range".to_string()));
                        }
                        0x14 => {
                            _result =
                                Some(Json::U64((output_stack[output_stack.len() - 2].clone())
                                    .as_u64()
                                    .unwrap() + 1));
                            codes.push(Json::String("single".to_string()));
                        }
                        0x15 => {
                            codes.push(Json::String("single".to_string()));
                            _result = Some(Json::U64(1));
                        }
                        0x16 => {
                            codes.push(Json::Array(vec![Json::String("c".to_string()),
                                                        (output_stack[output_stack.len() - 3]
                                                            .clone())]));
                            codes.push(Json::Array(vec![Json::String("c".to_string()),
                                                        (output_stack[output_stack.len() - 1]
                                                            .clone())]));
                            codes.push(Json::String("range".to_string()));
                            _result = Some(Json::U64(1));
                        }
                        0x17 => {
                            codes.push(Json::Array(vec![Json::String("c".to_string()),
                                                        (output_stack[output_stack.len() - 1]
                                                            .clone())]));
                        }
                        0x18 => {

                            if (output_stack[output_stack.len() - 1].clone())
                                .as_string()
                                .unwrap() == "\\c" {
                                return Err(lexer.new_lexer_error("Control Character".to_string()));
                            }
                            codes.push(Json::Array(vec![Json::String("escc".to_string()),
                                                        (output_stack[output_stack.len() - 1]
                                                            .clone())]));

                        }
                        _ => {}
                    };
                    if length > 0 && _result.is_none() {
                        _result = Some(output_stack[output_stack.len() - length].clone());
                    }
                    if _result.is_none() {
                        _result = Some(Json::Null);
                    }
                    {
                        let mut i = 0;
                        while i < length {
                            state_stack.pop();
                            output_stack.pop();
                            i += 1;
                        }
                    }
                    let next_state = state_stack[state_stack.len() - 1];
                    let next_action = self.lookup(self.prod_list[prod_index].header_id, next_state);
                    match next_action {
                        Action::Goto(next_state) => {
                            state_stack.push(next_state);
                            output_stack.push(_result.unwrap());
                        }
                        _ => return Err(lexer.new_lexer_error("Goto Error".to_string())),
                    };
                }
                _ => {
                    return Err(lexer.new_lexer_error("Parser Error".to_string()));
                }
            }
        }
        Ok(Json::Null)
    }
}
